version: "3.8"
services:
  influxdb2:
    image: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: telegraf
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: qwertyuiopasdfghjklzxcvbnm
    ports:
      - 9999:8086

  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000

  mqtt:
    image: hivemq/hivemq-ce
    ports:
      - 1883:1883

  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

  nodered:
    image: nodered/node-red #:latest-12
    ports:
      - 1880:1880
