version: "3.8"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    volumes:
    # - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/config:/etc/influxdb
    ports:
      - 8086:8086
  # restart: always | on-failure | unless-stopped

  kapacitor:
    image: kapacitor
    container_name: kapacitor
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    volumes:
      - ./kapacitor/data:/var/lib/kapacitor
      - ./kapacitor/config:/etc/kapacitor
    ports:
      - 9092:9092
  # restart: always | on-failure | unless-stopped

  chronograf:
    image: chronograf
    container_name: chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
    volumes:
      - ./chronograf/data:/var/lib/chronograf
    ports:
      - 8888:8888
  # restart: always | on-failure | unless-stopped

  influxdb2:
    image: influxdb:2.0
    container_name: influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: inter
      DOCKER_INFLUXDB_INIT_BUCKET: telegraf
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-auth-token
  # volumes:
  #   - ./influxdb2/data:/var/lib/influxdb2
  #   - ./influxdb2/config:/etc/influxdb2
    ports:
      - 9999:8086
  # restart: always | on-failure | unless-stopped

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - 3000:3000
  # restart: always | on-failure | unless-stopped

  mqtt:
  # image: hivemq/hivemq-ce
    image: eclipse-mosquitto #:1.6.12
    container_name: mqtt
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - 1883:1883
  # restart: always | on-failure | unless-stopped

  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  # restart: always | on-failure | unless-stopped

  mongo:
    image: mongo
    container_name: mongo
  # restart: always | on-failure | unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
  # restart: always | on-failure | unless-stopped

  nodered:
  # image: nodered/node-red
    build: .
    container_name: nodered
    volumes:
      - ./data:/data 
    ports:
      - 1880:1880
  # restart: always | on-failure | unless-stopped