version: "3.8"
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086

  kapacitor:
    image: kapacitor
    ports:
      - 9092:9092

  chronograf:
    image: chronograf
    ports:
      - 8888:8888

  influxdb2:
    image: influxdb:2.0
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: inter
      DOCKER_INFLUXDB_INIT_BUCKET: telegraf
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-auth-token
    ports:
      - 9999:8086

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000

  mqtt:
    image: hivemq/hivemq-ce
    ports:
      - 1880:1880

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

  nodered:
    image: nodered/node-red
    volumes:
      - ./data:/data
    ports:
      - 1880:1880
